latitude <- readLines('alltweetslat2.txt')
longitude <- readLines('alltweetslong2.txt')
WordCount <- as.numeric(readLines('tweetslength.txt'))
English <- as.numeric(readLines('Engwords.txt'))
Common <- as.numeric(readLines('comwords.txt'))
Tagalog <- as.numeric(readLines('tagwords.txt'))
Bikol <- as.numeric(readLines('bikwords.txt'))
Cebuano <- as.numeric(readLines('cebwords.txt'))
Hiligaynon <- as.numeric(readLines('hilwords.txt'))
Ilocano <- as.numeric(readLines('ilowords.txt'))
Kapampangan <- as.numeric(readLines('kapwords.txt'))
Pangasinense <- as.numeric(readLines('panwords.txt'))
Waray <- as.numeric(readLines('warwords.txt'))
Zam <- as.numeric(readLines('zamwords.txt'))
Spanish <- as.numeric(readLines('Spanishwords.txt'))
TagalogWordCount <- as.numeric(readLines('TagalogCountFromWindows.txt'))
length(TagalogWordCount)

tweets <- data.frame(latitude,longitude,WordCount,English,Common,Tagalog,Bikol,Cebuano,Hiligaynon,Ilocano,Kapampangan,Pangasinense,Waray,Zam,Spanish)
TagNonU <- data.frame(latitude, longitude, TagalogWordCount)
English <- data.frame(latitude, longitude, English)
Taglish <- data.frame(latitude, longitude, TagalogWordCount,English)


extract <- rbind(tweets[tweets$Bikol>2,], tweets[tweets$Cebuano>2,])
extract <- rbind(extract, tweets[tweets$Hiligaynon>2,])
extract <- rbind(extract, tweets[tweets$Ilocano>2,])
extract <- rbind(extract, tweets[tweets$Kapampangan>2,])
extract <- rbind(extract, tweets[tweets$Pangasinense>2,])
extract <- rbind(extract, tweets[tweets$Waray>2,])
extract <- rbind(extract, tweets[tweets$Zam>2,])
extract <- rbind(extract, tweets[tweets$Tagalog>2,])

write.csv(extract, 'extract 6-30.txt', row.names=TRUE)

